

@rem DO NOT EDIT THIS FILE

@rem To run: Open parent folder in Windows Explorer and double-click the .cmd file.

 

@echo off

echo Starting Sass Watch

 

rem This gets the folder location the file is executing in.

set "base=%~dp0"

set "file=SASS"

set "location=%base%%file%"

rem location of the Sass folder.

echo %location%

cd %location%

 

set "sassFile=App.scss"

set "targetFile=Main.css"

 

echo Reading %sassFile%

echo Writing %targetFile%

 

sass --watch %sassFile%:%targetFile% --style compressed
